### ISSUE TITLE
OCI Chart Not Published

### ISSUE THREAD

**Issue by milas** [woodpecker-ci/helm#135]
The docs reference the chart being published as an OCI artifact: `oci://registry-1.docker.io/woodpeckerci/helm` but there's nothing there at the moment: https://hub.docker.com/r/woodpeckerci/helm/tags

From what I can see in [`.woodpecker/release.yaml`](https://github.com/woodpecker-ci/helm/blob/03787ca00e3939ebebb5aafdcf730426dd826919/.woodpecker/release.yml#L15), there's no `helm push`.

Here's an example from a GHA workflow: https://github.com/prometheus-community/helm-charts/blob/ef3fe76dbb88ce712eaae22e8e14a868d41df061/.github/workflows/release.yaml#L53-L61
```bash
shopt -s nullglob
for pkg in .cr-release-packages/*; do
  if [ -z "${pkg:-}" ]; then
    break
  fi
  helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts"
done
```

**Comment by pat-s** [comment]
It has been decided to not publish an OCI chart, see #102. I'll tweak the README.

**Comment by milas** [comment]
Gotcha, no problem! The normal Helm repo works fine 🤠

Any reason you decided to not publish the OCI chart in the end?

**Comment by anbraten** [comment]
> Any reason you decided to not publish the OCI chart in the end?

It was quite tricky and the benefit was rather marginal IMO.
