### ISSUE TITLE
List of registered agents grows indefinitelly

### ISSUE THREAD

**Issue by vyskocilm** [woodpecker-ci/helm#148]
Agent configuration https://woodpecker-ci.org/docs/administration/agent-config#using-system-token says

> the agent registers to the server and store its unique id in a config file

Sadly this does not work well in k8s. The installed agents complaints about and as a consequence the list of registered agents grows all the time and I need to manually clean it up from time to time.

```
{"level":"error","error":"open /etc/woodpecker/agent.conf: no such file or directory","time":"2024-01-13T01:28:47Z","message":"could not persist agent config at '/etc/woodpecker/agent.conf'"}
```

Is it possible to address that somehow in helm? I am not an expert, so I have no idea if this is possible to do or if that require code changes.

**Comment by pat-s** [comment]
Discussed in https://github.com/woodpecker-ci/woodpecker/issues/3023

Right now, there is no way to change this.
