### ISSUE TITLE
Kubernetes default helm deployment configures github

### ISSUE THREAD

**Issue by Madic-** [woodpecker-ci/helm#2]
### Component

server

### Describe the bug

The default kubernetes helm deployment enables the github integration from woodpecker. But woodpecker can be used in scenarios without github integration. If someone does not want the github integration, it must be actively disabled.

My proposal is, to remove the github configs from the helm charts values.yml

```
env:
  WOODPECKER_GITHUB: true

extraSecretNamesForEnvFrom:
- woodpecker-github-client
- woodpecker-github-secret
```

With this change the documentation also needs to be adjusted.

### System Info

```shell
Helm chart for 0.15.x
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

**Comment by 6543** [comment]
closed by #7
