### ISSUE TITLE
Server pod errors out on fresh installation: could not setup service manager: forge not configured

### ISSUE THREAD

**Issue by kastl-ars** [woodpecker-ci/helm#202]
I just started playing around with woodpecker on Kubernetes (k3s in my case).

However even without any user-provided values the current chart version leads to failing pods in my tests:

```
$ helm install woodpecker woodpecker/woodpecker
[...]
$ kubectl logs woodpecker-server-0
{"level":"info","time":"2024-06-18T08:37:45Z","message":"log level: info"}
{"level":"fatal","error":"can't setup globals: could not setup service manager: forge not configured","time":"2024-06-18T08:37:45Z","message":"error running server"}
$
```

Is there something that I need to prepare before installation? If so, that step is missing in the [README](https://github.com/woodpecker-ci/helm/tree/main/charts/woodpecker#readme) (or I have completely missed it)...

Kind Regards,
Johannes

**Comment by pat-s** [comment]
As the error message tells you: it seems like you did not configure a forge (= Git Provider). WP won't start without it and it can't infer your git backend.

**Comment by kastl-ars** [comment]
Thanks for the fast reply!

If setting a forge is required it should be documented in the README and the `values.yaml`. (If I find time next week I can come up with a PR).

Also, unless I am missing something, neither the README.md nor the `values.yaml` contain any mention of the word `forge`. Which makes it extra difficult to find what there needs to configured.

(This might be obvious to someone running woodpecker in- and outside kubernetes for a long time, but for someone like me, just starting out with the helm chart, this is tough...)

**Comment by pat-s** [comment]
Yeah, I understand. It is the "classical" discussion of whether to provide non-meaningful defaults to avoid a "default" startup error or to require user input upfront.

[This page](https://woodpecker-ci.org/docs/administration/deployment/kubernetes) page could be a good start point to link the minimum config requirements to get going without any prior knowledge. It could reference [Forges](https://woodpecker-ci.org/docs/2.5/administration/forges/overview) and then be linked into the README of the helm chart?

Happy to take your suggestions which places might be best suited to place backrefs!

**Comment by anbraten** [comment]
I think a good way to start is to improve the guide "How to setup my own instance" in the docs and link this in the helm readme / comments.

https://github.com/woodpecker-ci/woodpecker/pull/3803

**Comment by kastl-ars** [comment]
> Yeah, I understand. It is the "classical" discussion of whether to provide non-meaningful defaults to avoid a "default" startup error or to require user input upfront.
> 
> [This page](https://woodpecker-ci.org/docs/administration/deployment/kubernetes) page could be a good start point to link the minimum config requirements to get going without any prior knowledge. It could reference [Forges](https://woodpecker-ci.org/docs/2.5/administration/forges/overview) and then be linked into the README of the helm chart?
> 
> Happy to take your suggestions which places might be best suited to place backrefs!

Thanks, I'll try to find some time to dig into this next week and report back. Maybe I can come up with a PR to add some things to the README or the values.yaml.

**Comment by pat-s** [comment]
Closing here as the upstream PR has been merged.
