### ISSUE TITLE
`helm repo add` not supported for OCI repos?

### ISSUE THREAD

**Issue by mhemken-vts** [woodpecker-ci/helm#238]
I tried to install and ran into an issue with `helm repo add`. It looks like helm does not support the `repo` subcommand for OCI repos (source: https://github.com/helm/helm/issues/10565#issuecomment-1015531100).

Or is that no longer the case?

I can submit a PR to update the docs. Just wanted to check first. Maybe there's something I don't know.

Error:
```
❯ helm repo add woodpecker oci://ghcr.io/woodpecker-ci/helm
Error: looks like "oci://ghcr.io/woodpecker-ci/helm" is not a valid chart repository or cannot be reached: object required
```

**Comment by pat-s** [comment]
Ah yes, it should only be `helm install` for OCI. But in any case, the OCI packages don't exist yet (see >= 1.6.1).

**Comment by anbraten** [comment]
https://github.com/woodpecker-ci/helm/pkgs/container/helm%2Fwoodpecker

So should be available as: `oci://ghcr.io/woodpecker-ci/helm/woodpecker` now
