### ISSUE TITLE
Default version v0.15.9 doesn't appear to actually support kubernetes

### ISSUE THREAD

**Issue by Rojikku** [woodpecker-ci/helm#46]
Hello there. I am experimenting with this project for a friend who wants to use it in their business, and might end up using it myself, we'll see.

During the deployment, I encountered the following issues:
1. As mentioned by #45, the helm chart I was supposed to use changed, but nobody told me in the docs. So I was trying to deploy an old, buggy helm chart, which was not a good time.
2. I got a significant number of complaints from woodpecker-agent about how kubernetes was not a valid backend. In other words, your chart is deploying an invalid configuration, which is an...interesting choice? I would make this a bug under woodpecker, if it's a regression, but further research, from what I can tell, shows that the kubernetes integration is new- even though this repo has existed since 2021- and this might be expected behavior. It is fixed in the latest version of next, as well. But there are no notes about this, and the repo isn't using a version that actually supports kubernetes, which is disappointing.

Even if you don't fix this, at least leave this issue open for people to find quick answers to their problem if they encounter the same one.

I got it working here:
[HelmRelease](https://github.com/Rojikku/home-ops/blob/main/cluster/apps/runners/woodpecker/app/helmrelease.yaml)
[Permalink](https://github.com/Rojikku/home-ops/blob/c88068ab3b1a8fc06179bb01feb28dffd6fcbd59/cluster/apps/runners/woodpecker/app/helmrelease.yaml)

Granted, I haven't tested any pipelines, but everything turned on and the webpage loaded, so it probably works.

Thanks for the project!

**Comment by 6543** [comment]
yes kubernetes support is added only in next and will be published with v1.0.0

the docs shold also reflect that ...

for now you need to use next .
PS: you can pin next by next-`someCommitID[10]`

as for the chart ... I think you used the stable tag witch resulted in this ... well chart related issues are now tracked in our chart repo :)

**Comment by Rojikku** [comment]
> yes kubernetes support is added only in next and will be published with v1.0.0
> 
> the docs shold also reflect that ...
> 
> for now you need to use next . PS: you can pin next by next-`someCommitID[10]`

Exactly what I did!

> as for the chart ... I think you used the stable tag witch resulted in this ... well chart related issues are now tracked in our chart repo :)

I used the default, yes.

**Comment by ymettier** [comment]
It works with Kubernetes for me.

```
➜ cat ../values.yaml 
---
server:
  image:
    tag: next-3033abc3b4
[...]
agent:
  image:
    tag: next-3033abc3b4
[...]
```

Then
```
helm repo add woodpecker https://woodpecker-ci.org/
helm repo update
helm upgrade --install --atomic woodpecker --namespace woodpecker woodpecker/woodpecker -f values.yaml --version 0.1.5
```

Of course it should also work with `tag: next`.

*Note for maintainers* : if you do not specify `--version 0.1.5` it will download *highest* version (not latest) which is `0.15.6` or something similar.

**Comment by anbraten** [comment]
https://github.com/woodpecker-ci/helm/issues/45 will solve the versioning. Apart from that next can be used and 1.0.0 should be released soonishly
