### ISSUE TITLE
Documentation for installing current release?

### ISSUE THREAD

**Issue by dominic-p** [woodpecker-ci/helm#65]
I'm struggling a bit to understand the proper method to install this chart. From [the docs](https://woodpecker-ci.org/docs/administration/kubernetes#preparation) it seems like we should install from the helm repo at https://woodpecker-ci.org/. The ["next" branch docs](https://woodpecker-ci.org/docs/next/administration/setup#kubernetes) don't give specific install instructions (they just link to this repo). But, this is what I'm seeing:

```
$ helm repo add woodpecker https://woodpecker-ci.org
"woodpecker" has been added to your repositories

$ helm search repo woodpecker
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
woodpecker/woodpecker   0.1.5           v0.15.9         A Helm chart for Woodpecker CI
```

It looks like the most recent version available is 0.1.5, but on GitHub I see a [0.3.0 release](https://github.com/woodpecker-ci/helm/releases/tag/0.3.0) from a couple of days ago. Is there another repo where the more recent releases are available? I apologize for the basic question. I'm still fairly new to helm, and I might be missing something very obvious.

This might be related to #45, but I'm not sure.

**Comment by anbraten** [comment]
We have some issues with releasing new versions therefore the GitHub release git created, but we could not release a new helm version yet

**Comment by anbraten** [comment]
We finally fixed the release:

```
$ helm search repo woodpecker
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION                   
woodpecker/woodpecker	0.3.2        	v1.0.0     	A Helm chart for Woodpecker CI
```
