### ISSUE TITLE
Ability to add additional volumes to the server

### ISSUE THREAD

**Issue by dominic-p** [woodpecker-ci/helm#79]
I'm trying to make a container registry config available [as described here](https://woodpecker-ci.org/docs/administration/server-config#global-registry-setting). The easiest way I can see to do that would be to mount a Secret containing the docker config file and then set the `WOODPECKER_DOCKER_CONFIG` to match the path where I mounted the file. However, I can't seem to find a good way to mount the config file in the server container.

Maybe we could add `extraVolumeMounts:` and `extraVolumes:` to the server values?

**Comment by CrimsonFez** [comment]
they exist already. documentation doesn't reflect it though. PR is already open to fix this issue :)

**Comment by dominic-p** [comment]
Thanks for sharing that. Looking closer at the charts, it looks like the configuration currently exists for the agent chart, but I'm not seeing it in the [server template](https://github.com/woodpecker-ci/helm/blob/0.3.2/charts/server/templates/statefulset.yaml). Am I missing it again?

It does look like `WOODPECKER_DOCKER_CONFIG ` needs to be set on the server.

**Comment by pat-s** [comment]
Jup `extraVolumes` and mounts are still missing for the `server` at the moment.
